
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 20 2025 23:28:59 +07 (Nov 20 2025 16:28:59 UTC)

// Verification Directory fv/ex4 

module ex4(clk, rst, Q);
  input clk, rst;
  output [1:0] Q;
  wire clk, rst;
  wire [1:0] Q;
  wire n_0, n_1, n_2;
  DFFHQX1HVT \Q_reg[1] (.CK (clk), .D (n_2), .Q (Q[1]));
  NOR2XLHVT g20__2398(.A (rst), .B (n_1), .Y (n_2));
  DFFHQX1HVT \Q_reg[0] (.CK (clk), .D (n_0), .Q (Q[0]));
  XNOR2X1HVT g22__5107(.A (Q[0]), .B (Q[1]), .Y (n_1));
  NOR2XLHVT g23__6260(.A (rst), .B (Q[0]), .Y (n_0));
endmodule

