
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 21 2025 16:25:38 +07 (Nov 21 2025 09:25:38 UTC)

// Verification Directory fv/fa1 

module fa1(A, B, CIN, SUM, COUT);
  input A, B, CIN;
  output SUM, COUT;
  wire A, B, CIN;
  wire SUM, COUT;
  ADDFX1LVT g85__2398(.A (B), .B (A), .CI (CIN), .CO (COUT), .S (SUM));
endmodule

