
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 20 2025 22:05:01 +07 (Nov 20 2025 15:05:01 UTC)

// Verification Directory fv/fa1 

module fa1(A, B, CIN, SUM, COUT);
  input A, B, CIN;
  output SUM, COUT;
  wire A, B, CIN;
  wire SUM, COUT;
  ADDFX1HVT g85__2398(.A (A), .B (B), .CI (CIN), .CO (COUT), .S (SUM));
endmodule

