
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 19 2025 09:09:04 +07 (Nov 19 2025 02:09:04 UTC)

// Verification Directory fv/ex2 

module ex2(A, B, S, Y);
  input [1:0] A, B, S;
  output [1:0] Y;
  wire [1:0] A, B, S;
  wire [1:0] Y;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_9;
  MX2XLHVT g364__2398(.A (n_9), .B (n_3), .S0 (S[1]), .Y (Y[1]));
  XNOR2X1HVT g367__5107(.A (n_0), .B (n_6), .Y (n_9));
  OAI21XLHVT g365__6260(.A0 (S[1]), .A1 (n_2), .B0 (n_7), .Y (Y[0]));
  OAI2BB1X1HVT g368__4319(.A0N (n_5), .A1N (n_4), .B0 (S[1]), .Y (n_7));
  NOR2BX1HVT g370__8428(.AN (n_5), .B (n_4), .Y (n_6));
  OAI2BB1X1HVT g366__5526(.A0N (B[1]), .A1N (A[1]), .B0 (n_1), .Y
       (n_3));
  XNOR2X1HVT g372__6783(.A (B[0]), .B (A[0]), .Y (n_2));
  OAI21XLHVT g369__3680(.A0 (B[1]), .A1 (A[1]), .B0 (S[0]), .Y (n_1));
  XNOR2X1HVT g373__1617(.A (B[1]), .B (A[1]), .Y (n_0));
  OAI21XLHVT g371__2802(.A0 (S[0]), .A1 (A[0]), .B0 (B[0]), .Y (n_4));
  NAND2XLHVT g374__1705(.A (S[0]), .B (A[0]), .Y (n_5));
endmodule

