
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 18 2025 05:36:27 +07 (Nov 17 2025 22:36:27 UTC)

// Verification Directory fv/nor2 

module nor2(A, B, Y);
  input A, B;
  output Y;
  wire A, B;
  wire Y;
  NOR2XLLVT g13__2398(.A (B), .B (B), .Y (Y));
endmodule

