
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 18 2025 05:22:16 +07 (Nov 17 2025 22:22:16 UTC)

// Verification Directory fv/or2 

module or2(A, B, Y);
  input A, B;
  output Y;
  wire A, B;
  wire Y;
  OR2XLLVT g2__2398(.A (A), .B (B), .Y (Y));
endmodule

