
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 22 2025 17:40:15 +07 (Nov 22 2025 10:40:15 UTC)

// Verification Directory fv/dff 

module dff(i_d, i_clk, o_q);
  input i_d, i_clk;
  output o_q;
  wire i_d, i_clk;
  wire o_q;
  DFFHQX1HVT o_q_reg(.CK (i_clk), .D (i_d), .Q (o_q));
endmodule

