
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 20 2025 19:18:23 +07 (Nov 20 2025 12:18:23 UTC)

// Verification Directory fv/mux2 

module mux2(D0, D1, S, Y);
  input D0, D1, S;
  output Y;
  wire D0, D1, S;
  wire Y;
  MX2XLHVT g28__2398(.A (D0), .B (D1), .S0 (S), .Y (Y));
endmodule

