
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 18 2025 05:29:48 +07 (Nov 17 2025 22:29:48 UTC)

// Verification Directory fv/nand2 

module nand2(A, B, Y);
  input A, B;
  output Y;
  wire A, B;
  wire Y;
  NAND2XLHVT g4__2398(.A (A), .B (B), .Y (Y));
endmodule

