
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 18 2025 04:58:19 +07 (Nov 17 2025 21:58:19 UTC)

// Verification Directory fv/not1 

module not1(A, Y);
  input A;
  output Y;
  wire A;
  wire Y;
  INVXLLVT g2(.A (A), .Y (Y));
endmodule

